= Journée du LAMSADE 2019

La journée du Lamsade aura lieu le 18 avril.

Format de l’année dernière : 10 + 20 + 40 + 20 + 15 + 40 + 20 + 15 + 15 + 40 + 10 + 40 + 10 + 20 + 40 + 15 + 30 = 400 minutes

e-mail Laurent 5 février :

merci d'avoir accepté la difficile mais hautement gratifiante mission d'organiser la journée du LAMSADE pour 2019. Comme d'habitude ça se passera à l'IHP. Eleni a fait une réservation d'un amphi (18 avril), et d'une autre salle pour les pause café/déjeuner. Il y a aura des travaux dans le hall de l'IHP mais la salle pour les pauses et autre ne seront pas loin. Marie-Clotilde se charge de la réservation du resto le soir. Restez en lien avec Eleni et Marie pour caler horaires des pauses café et déjeuner. Sinon vous pouvez solliciter Hawa pour rédiger le programme. Merci de lui communiquer le plus en avance possible pour diffusion.

Pour l'aspect scientifique c'est vous les maîtres à bord. N'hésitez pas à vous rapprocher de l'équipe de l'an passé pour partager leur expérience (si ma mémoire est bonne, Denis était déjà là). Et n'hésitez pas à vous manifester s'il y a un besoin matériel quelconque dans votre projet (nous avions par exemple eu besoin d'un espace et de matériel pour les posters il y a 3 ans).


